services:
  opnsense-vpn-monitor:
    image: ${DOCKER_IMAGE:-ghcr.io/curiohokiest2e/opnsense-vpn-monitor:latest}
    container_name: opnsense-vpn-monitor
    env_file:
      - .env
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - CHECK_INTERVAL=${CHECK_INTERVAL}
    restart: unless-stopped